pacman_packages:
- bash-completion
- gvim
- git
- tig
- base-devel
- gnu-netcat
- net-tools
- traceroute
- htop
- atop
- strace
- ltrace
- kitty
- ranger
- yay
# desktop applications
- firefox
- vlc
- thunderbird
- libreoffice-still
- chromium
- flatpak
- signal-desktop
# Docker
- docker
- docker-buildx
- docker-compose
# K8s
- kubectl
- helm
- minikube
# Python
- python
- python-pip
# Go
- go
- gopls
# Neovim
- neovim
- ripgrep
- fd

aur_packages:
- skaffold-bin
- kafkacat-git
- neovim-plug

flatpak_packages:
- io.github.spacingbat3.webcord
