[tool.ruff]
line-length = 79

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN101",
  "COM812",
  "CPY001",
  "FBT",
  "ISC001",
  "SIM105",
]
