- name: upgrade AUR packages
  kewlfft.aur.aur:
    update_cache: yes
    upgrade: yes
    use: yay
    aur_only: yes
- name: update flatpak packages
  ansible.builtin.command: flatpak update --noninteractive
- name: run "pacman -Syu"
  become: true
  community.general.pacman:
    update_cache: true
    upgrade: true
