- name: run "pacman -Sy"
  become: true
  community.general.pacman:
    update_cache: true
- name: install pacman packages
  become: true
  community.general.pacman:
    name: "{{ pacman_packages }}"
- name: add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
- name: enable docker systemd service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    masked: no
- name: install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
- name: install AUR packages
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
  loop: "{{ aur_packages }}"
