---
- name: error
  ansible.builtin.fail:
    msg: variable vault_path is required
  when: vault_path == ""
- name: copy host to vault
  become: true
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ vault_path }}/{{ item.dest }}"
    owner: true
    group: true
    recursive: true
    delete: true
  loop: "{{ host2vault }}"
  when: vault_path != ""
